interface Question {
  id: number;
  text: string;
  answers: string[];
  leven: number;
  points: number;
}

interface Category {
  id: number;
  name: string;
  questions: Question[];
}

const categories: Category[] = [
  {
    id: 1,
    name: "Historie",
    questions: [
      {
        id: 1,
        text: "Kdo byl první prezident Československé republiky?",
        answers: ["Tomáš Garrigue Masaryk", "Masaryk"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "V kterém roce vznikla Česká republika?",
        answers: ["1993"],
        leven: 0,
        points: 200,
      },
      {
        id: 3,
        text: "Kde se nachází hrad Karlštejn?",
        answers: ["Středočeský kraj"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Která dynastie vládla v Čechách nejdéle?",
        answers: ["Habsburkové"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Kdy proběhla sametová revoluce?",
        answers: ["1989"],
        leven: 0,
        points: 500,
      },
      {
        id: 6,
        text: "Kdo byl poslední rakousko-uherský císař?",
        answers: ["Karel I.", "Karel"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 2,
    name: "Zeměpis",
    questions: [
      {
        id: 1,
        text: "Jaká je nejvyšší hora v Česku?",
        answers: ["Sněžka"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Která řeka protéká Prahou?",
        answers: ["Vltava"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Kolik krajů má Česká republika?",
        answers: ["14"],
        leven: 0,
        points: 300,
      },
      {
        id: 4,
        text: "Které město je neoficiálně nazýváno hlavním městem Moravy?",
        answers: ["Brno"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "S kolika zeměmi hraničí Česká republika?",
        answers: ["4"],
        leven: 0,
        points: 500,
      },
      {
        id: 6,
        text: "Jak se jmenuje největší přirozené jezero v Čechách?",
        answers: ["Černé jezero"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 3,
    name: "Sport",
    questions: [
      {
        id: 1,
        text: "Který český hokejista je považován za jednoho z nejlepších na světě a hrál v NHL nejvíce zápasů?",
        answers: ["Jaromír Jágr", "Jágr"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "V kterém roce vyhrála česká fotbalová reprezentace mistrovství Evropy?",
        answers: ["1976"],
        leven: 0,
        points: 200,
      },
      {
        id: 3,
        text: "Která česká tenistka vyhrála Wimbledon v roce 2011?",
        answers: ["Petra Kvitová", "Kvitová"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Kolik zlatých medailí získal Emil Zátopek na olympiádě v Helsinkách?",
        answers: ["3"],
        leven: 0,
        points: 400,
      },
      {
        id: 5,
        text: "Jak se jmenuje nejvyšší česká fotbalová liga?",
        answers: ["Fortuna Liga"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Který český biatlonista vyhrál celkový Světový pohár?",
        answers: ["Ondřej Moravec", "Moravec"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 4,
    name: "Kultura",
    questions: [
      {
        id: 1,
        text: "Kdo napsal Babičku?",
        answers: ["Božena Němcová", "Němcová"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Jak se jmenuje hlavní postava z díla Osudy dobrého vojáka Švejka?",
        answers: ["Josef Švejk", "Švejk"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Který český skladatel složil operu Prodaná nevěsta?",
        answers: ["Bedřich Smetana", "Smetana"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Kdo je autorem románu Krysař?",
        answers: ["Viktor Dyk", "Dyk"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Který český básník napsal Máj?",
        answers: ["Karel Hynek Mácha", "Mácha"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Jak se jmenuje slavný český kreslíř a ilustrátor krtečka?",
        answers: ["Zdeněk Miler", "Miler"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 5,
    name: "Filmy",
    questions: [
      {
        id: 1,
        text: "Který český film režíroval Jiří Menzel a vyhrál Oscara?",
        answers: ["Ostře sledované vlaky"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Kdo hrál hlavní roli ve filmu Pelíšky?",
        answers: ["Jiří Kodet", "Kodet"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Který český režisér natočil film Amadeus?",
        answers: ["Miloš Forman", "Forman"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Jak se jmenuje hlavní postava z filmu Marečku, podejte mi pero!?",
        answers: ["Marek Eben", "Eben"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Který český film z roku 1966 je považován za jeden z nejlepších?",
        answers: ["Obchod na korze"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Kdo režíroval film Hoří, má panenko?",
        answers: ["Miloš Forman", "Forman"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 6,
    name: "Hudba",
    questions: [
      {
        id: 1,
        text: "Kto je zpěvák skupiny Olympic?",
        answers: ["Petr Janda", "Janda"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Která česká zpěvačka zpívala píseň Láska je láska?",
        answers: ["Helena Vondráčková", "Vondráčková"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Jak se jmenuje slavný český houslista známý svým nekonvenčním stylem a elektrickou houslí?",
        answers: ["Pavel Šporcl", "Šporcl"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Která skupina nazpívala píseň Duhová víla?",
        answers: ["Elán"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Kdo složil hudbu k filmu Pelíšky?",
        answers: ["Aleš Březina", "Březina"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Který český dirigent vedl Českou filharmonii?",
        answers: ["Václav Talich", "Talich"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 7,
    name: "Jídlo",
    questions: [
      {
        id: 1,
        text: "Jaký je nejpopulárnější český pokrm?",
        answers: ["Svíčková na smetaně"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Jak se jmenuje tradiční česká polévka ze zelí?",
        answers: ["Zelňačka"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Který český dezert se připravuje z tvarohu a vajec?",
        answers: ["Tvarohové knedlíky"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Jaká je hlavní ingredience goulášové polévky?",
        answers: ["Hovězí maso"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Která česká značka piva je nejstarší?",
        answers: ["Pilsner Urquell"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Jak se jmenuje tradiční moravský dezert s mákem?",
        answers: ["Makovec"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 8,
    name: "Věda",
    questions: [
      {
        id: 1,
        text: "Jaký je chemický vzorec vody?",
        answers: ["H2O"],
        leven: 0,
        points: 100,
      },
      {
        id: 2,
        text: "Která planeta je nejblíže ke Slunci?",
        answers: ["Merkur"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Jak se jmenuje proces, při kterém rostliny vyrábějí kyslík?",
        answers: ["Fotosyntéza"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Který český vědec objevil krevní skupiny?",
        answers: ["Jan Janský", "Janský"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Kolik chromozomů má člověk?",
        answers: ["46"],
        leven: 0,
        points: 500,
      },
      {
        id: 6,
        text: "Který český chemik a vynálezce kontaktních čoček získal Nobelovu cenu za chemii?",
        answers: ["Jaroslav Heyrovský", "Heyrovský"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 9,
    name: "Příroda",
    questions: [
      {
        id: 1,
        text: "Které zvíře je symbolem České republiky?",
        answers: ["Lev"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Jak se jmenuje největší český národní park?",
        answers: ["Krkonošský národní park"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Která dravá ryba je považována za králici českých řek?",
        answers: ["Štika"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Který strom je národním stromem České republiky?",
        answers: ["Lípa"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Kolik národních parků má Česká republika?",
        answers: ["4"],
        leven: 0,
        points: 500,
      },
      {
        id: 6,
        text: "Která česká hora je považována za kolébku českého národa podle legendy?",
        answers: ["Říp"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 10,
    name: "Umění",
    questions: [
      {
        id: 1,
        text: "Kdo namaloval obraz Slovanská epopej?",
        answers: ["Alfons Mucha", "Mucha"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Který český sochař vytvořil sochu sv. Václava na Václavském náměstí?",
        answers: ["Josef Václav Myslbek", "Myslbek"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Jak se jmenuje slavný český kreslíř a ilustrátor pohádek o Švejkovi?",
        answers: ["Josef Lada", "Lada"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Který český malíř impresionista je známý svými krajinami a působil v Paříži?",
        answers: ["Antonín Slavíček", "Slavíček"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Kdo navrhl Tančící dům v Praze?",
        answers: ["Vlado Milunić", "Milunić"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Který český malíř byl jedním ze zakladatelů skupiny Osma?",
        answers: ["Emil Filla", "Filla"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 11,
    name: "Politika",
    questions: [
      {
        id: 1,
        text: "Kdo je současný prezident České republiky?",
        answers: ["Petr Pavel", "Pavel"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Kdy vstoupila Česká republika do EU?",
        answers: ["2004"],
        leven: 0,
        points: 200,
      },
      {
        id: 3,
        text: "Kdo byl prvním prezidentem České republiky?",
        answers: ["Václav Havel", "Havel"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Kolik členů má Poslanecká sněmovna?",
        answers: ["200"],
        leven: 0,
        points: 400,
      },
      {
        id: 5,
        text: "Kdy vstoupila Česká republika do NATO?",
        answers: ["1999"],
        leven: 0,
        points: 500,
      },
      {
        id: 6,
        text: "Kdo byl posledním komunistickým prezidentem Československa?",
        answers: ["Gustáv Husák", "Husák"],
        leven: 1,
        points: 600,
      },
    ],
  },
  {
    id: 12,
    name: "Technika",
    questions: [
      {
        id: 1,
        text: "Který český vynálezce sestrojil první telegraf?",
        answers: ["Pavel Kabík", "Kabík"],
        leven: 1,
        points: 100,
      },
      {
        id: 2,
        text: "Jak se jmenuje český operační systém?",
        answers: ["ReactOS"],
        leven: 1,
        points: 200,
      },
      {
        id: 3,
        text: "Která česká společnost založená v roce 1988 vyrábí protivirové programy?",
        answers: ["Avast"],
        leven: 1,
        points: 300,
      },
      {
        id: 4,
        text: "Kdo vynalezl měkké kontaktní čočky?",
        answers: ["Otto Wichterle", "Wichterle"],
        leven: 1,
        points: 400,
      },
      {
        id: 5,
        text: "Která česká firma je známá výrobou her DayZ a Arma?",
        answers: ["Bohemia Interactive"],
        leven: 1,
        points: 500,
      },
      {
        id: 6,
        text: "Jak se jmenuje český supercomputer?",
        answers: ["Salomon"],
        leven: 1,
        points: 600,
      },
    ],
  },
];

export { categories, type Category, type Question };
